### ISSUE TITLE
HTTPS Request Error

### ISSUE THREAD

**Issue by tutrieuchau** [yacchin1205/pepper-web-boxes#2]
When I use google cloud vision label detect box, i got error "No module Requests ". And then i add module requests to pepper lib. But i got error "Can't connect to HTTPS URL because the SSL module is not available". I think pepper do not support HTTPS request. Can you tell me how you can get google cloud vision without that error?
Thank you,

**Comment by tutrieuchau** [comment]
I find out this problem cause Pepper Virtual (Window) does not support HTTPS

**Comment by yacchin1205** [comment]
Thank you for reporting your issue!
I've seen that virtual robot on Mac has SSL module... Perhaps you can use the box on Mac. 😃
